### ISSUE TITLE
Timer interrupt example doesn't compile

### ISSUE THREAD

**Issue by paradajz** [f32c/arduino#25]
IDE: Arduino IDE 1.6.9
OS: Windows 10 x64

Description: Selecting "mips_timer" example under "f32c/interrupts" cannot compile because of following reason:

`"VARIANT_MCK' was not declared in this scope`

**Comment by emard** [comment]
Replace VARIANT_MCK with F_CPU for quick fix
until I relase to nxlab new stuff, probably next week

But now I see that this interrupt is not working as it
should. It runs for some time and stops.

Problem is more deep than it seems, there's bug/feature?
in f32c core that MUL instruction is not allowed to be executed in 
interrupt context.

**Comment by emard** [comment]
Hopefully fixed, raise new issue in case of further problems
