### ISSUE TITLE
tools bin folder is empty 

### ISSUE THREAD

**Issue by goran-mahovlic** [f32c/arduino#5]
Cannot run program "C:\Users\gmahovlic\AppData\Roaming\Arduino15\packages\FPGArduino\tools\f32c-compiler\1.0.0\bin\mips-elf-g++" (in directory "."): CreateProcess error=2, The system cannot find the file specified

**Comment by emard** [comment]
I checked board manager json few minutes ago on some xp and all compiler
components work, correctly compile blink, SD, adafruit ssd1306

**Comment by goran-mahovlic** [comment]
I have deleted all and download it again, now it is working, probably arduino some times does not download all files...
