### ISSUE TITLE
SPI example will not link

### ISSUE THREAD

**Issue by emard** [f32c/arduino#7]
They used to compile, but now I don't know whazzup
examples->SPI->DigitalPotControl
/tmp/build1904330117572721905.tmp/DigitalPotControl.cpp.o: In function `setup':
(.text.setup+0x18): undefined reference to`SPI'

**Comment by gornjas** [comment]
The problem seems to be (again) that when SPI.cpp is compiled, SPI_INTERFACES_COUNT is not greater than zero, so SPIClass SPI() instantiation at line 614 is getting wiped out by complier's preprocessor.

**Comment by emard** [comment]
I defined SPI_INTERFACES_COUNT in SPI.h now it compiles.
Code is empty, just a placeholder to add hardware SPI support
